
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

/**
 *
 * @author aakas
 */
public class scoreTaker extends javax.swing.JFrame {

    /**
     * Creates new form scoreTaker
     */

    public scoreTaker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        title = new javax.swing.JLabel();
        CETscore = new javax.swing.JTextField();
        cetlabel = new javax.swing.JLabel();
        genderlabel = new javax.swing.JLabel();
        categoryBox = new javax.swing.JComboBox<>();
        categorylabel = new javax.swing.JLabel();
        predict = new javax.swing.JButton();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("How did you fare?");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 320, 50));

        CETscore.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CETscore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CETscoreActionPerformed(evt);
            }
        });
        getContentPane().add(CETscore, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 73, 196, 46));

        cetlabel.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        cetlabel.setForeground(new java.awt.Color(255, 255, 255));
        cetlabel.setText("CET Score");
        getContentPane().add(cetlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 170, 37));

        genderlabel.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        genderlabel.setForeground(new java.awt.Color(255, 255, 255));
        genderlabel.setText("Gender");
        getContentPane().add(genderlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 120, 35));

        categoryBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        categoryBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "SC", "ST", "OBC", "TFWS", "PWD", "EWS", "VJ", "NT1", "NT2", "NT3" }));
        categoryBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryBoxActionPerformed(evt);
            }
        });
        getContentPane().add(categoryBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 202, 43));

        categorylabel.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        categorylabel.setForeground(new java.awt.Color(255, 255, 255));
        categorylabel.setText("Category");
        getContentPane().add(categorylabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 140, 40));

        predict.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        predict.setText("PREDICT NOW");
        predict.setActionCommand("PREDICT NOW!");
        predict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                predictActionPerformed(evt);
            }
        });
        getContentPane().add(predict, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 382, 250, 58));

        male.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setText("MALE");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        getContentPane().add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 166, -1, -1));

        female.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("FEMALE");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        getContentPane().add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 190, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/NetBeansProjects/JavaMiniProject/src/main/img/college copy 2.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 678, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CETscoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CETscoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CETscoreActionPerformed

    private void categoryBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryBoxActionPerformed

    private void predictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_predictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_predictActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(scoreTaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(scoreTaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(scoreTaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scoreTaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new scoreTaker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CETscore;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> categoryBox;
    private javax.swing.JLabel categorylabel;
    private javax.swing.JLabel cetlabel;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel genderlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton male;
    private javax.swing.JButton predict;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
